### ISSUE TITLE
Error Compiling Asteroids Example

### ISSUE THREAD

**Issue by andrewexton373** [johanhelsing/noisy_bevy#5]
Hello,

I'm pretty sure the dependency for bevy_egui can be updated as there's a tagged release with support for bevy 0.10 now. Let me know if I can assist with this.

```rust
cargo run --example asteroids_example
    Updating crates.io index
    Updating git repository `https://github.com/mvlabat/bevy_egui`
error: failed to get `bevy_egui` as a dependency of package `noisy_bevy v0.3.0 (C:\Users\andre\Development\noisy_bevy)`

Caused by:
  failed to load source for dependency `bevy_egui`

Caused by:
  Unable to update https://github.com/mvlabat/bevy_egui?branch=bevy-0.10

Caused by:
  failed to find branch `bevy-0.10`

Caused by:
  cannot locate remote-tracking branch 'origin/bevy-0.10'; class=Reference (4); code=NotFound (-3)
PS C:\Users\andre\Development\noisy_bevy>
```

**Comment by andrewexton373** [comment]
Using these in the cargo.toml allows me to compile this fine, however it looks as if there are regressions in the runtime results:

```rust
bevy_egui = {version = "0.20.1", default-features = false, features = ["default_fonts"]}
bevy_pancam = {version = "0.8", features = ["bevy_egui"] }
```

<img width="420" alt="Screenshot 2023-03-22 140303" src="https://user-images.githubusercontent.com/5461576/227037566-f240df22-bb98-41ec-8364-8dd8a67a35c5.png">

![68747470733a2f2f73332e6a6f68616e68656c73696e672e73747564696f2f64756d702f6e6f6973795f61737465726f69642e706e67](https://user-images.githubusercontent.com/5461576/227038086-d4e7b865-e1fb-48cf-bd06-bdf462fb781c.png)

**Comment by johanhelsing** [comment]
What is the regression?

**Comment by johanhelsing** [comment]
Happy to accept a PR bumping to the latest version, btw

**Comment by andrewexton373** [comment]
The images I attached in my previous comment should hopefully highlight the potential regression. It seems like it broke the bevy_egui panel and the rendering of the asteroid. I hadn’t compiled this project until today, so it’s possible I’m wrong about this. I’ll make a PR of the version bump.

**Comment by andrewexton373** [comment]
I've created a PR with the version bumps: #6

**Comment by johanhelsing** [comment]
The rendering i think I was already like that. The example used to depend on bevy_smud, but i removed it to reduce deps and make it easier to understand.

The inspector panel is supposed to be there, and is disabled because i wanted a bevy 0.10 compatible release and bevi-isnspector-egui wasn't ready yet.
